# QUESTIONS:
-- Q1. What are the names of all the countries in the country table?
select*from country ;
select country_name from country;

-- Q2.What is the total number of customers in the customers table?
SELECT *FROM customers; 
select count(*)FROM customers; #8 customers 
-- Q3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
SELECT AVG(age) AS average_age
FROM customers
WHERE can_email = 'yes'; # 37,000
-- Q4.How many orders were made by customers aged 30 or older?
select *from orders;
SELECT COUNT(*) AS order_count
FROM orders
WHERE customer_id IN (
    SELECT customer_id
    FROM customers
    WHERE age >= 30 # 3 orders 
);
-- Q5. What is the total revenue generated by each product category?
SELECT *FROM products;
SELECT category, SUM(price) AS total_revenue
FROM products
GROUP BY category;

-- Q6 .What is the average price of products in the 'food' category?
SELECT *FROM products;
SELECT AVG(price) AS average_price
FROM products
WHERE category = 'food'; #'3.440000'

-- Q7. How many orders were made in each sales channel (sales_channel column) in the orders table?
select *from orders;
SELECT sales_channel, COUNT(*) AS order_count
FROM orders
GROUP BY sales_channel; #retail : 5 and online:3 
-- Q8. What is the date of the latest order made by a customer who can receive marketing emails?
SELECT *FROM customers;
#use subquery :
SELECT MAX(date_shop) AS latest_order_date
FROM orders
WHERE customer_id IN (
    SELECT customer_id
    FROM customers
    WHERE can_email = 'yes'
);
-- Q9. What is the name of the country with the highest number of orders?
select *from country;
SELECT c.country_name
FROM country c
JOIN orders o ON c.country_id = o.country_id
GROUP BY c.country_name
ORDER BY COUNT(*) DESC
LIMIT 1; #uK 
-- Q10. What is the average age of customers who made orders in the 'vitamins' product category?
SELECT AVG(c.age) AS average_age
FROM customers c, orders o, baskets b, products p #alias 3 tables fetch 
WHERE c.customer_id = o.customer_id
AND o.order_id = b.order_id
AND b.product_id = p.product_id
AND p.category = 'vitamins'; # '29.7143'




